[package]
name = "trace4rs"
version = "0.1.0"
edition = "2021"
description = "log4rs like usability with the `tracing` crate as the base"
keywords = ["tracing", "logging", "log4rs"]
authors = ["Evan Simmons", "Everett Pompeii", "Richard Meester"]

[features]
tracing-macros = []

[dependencies]
literally = "0.1.3"
log = "0.4.14"
once_cell = "1.8.0"
parking_lot = "0.11.2"
regex = "1.5.4"
thiserror = "1.0.29"
tracing = "0.1.0"
tracing-subscriber = { version = "0.3", features = [
    "std",
    "fmt",
    "time",
    "local-time",
    "registry",
] }
tracing-log = "0.1.2"
time = { version = "0.3.5", features = ["formatting", "macros"] }
path-absolutize = "3.0.11"
trace4rs_config = {path = "../config"}
fmtorp = { version = "0.1.0", path = "../fmtorp" }

[dev-dependencies]
criterion = "0.3.5"
criterion-macro = "0.3.4"
literally = "0.1.3"
log4rs = "1.0.0"
serde = "1.0.130"
serde_json = "1.0.68"
static_assertions = "1.1.0"
tempfile = "3.2.0"
tokio = { version = "1.13.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "time",
    "fs",
] }
trace4rs_config = {path = "../config", features = ["in-order-serialization"]}

[[bench]]
name = "trace4rs_bench"

[[bench]]
name = "log4rs_bench"
