name: Benchmark

on:
  pull_request_target:
  push:
    branches:
      - main
      - 'feature-**'

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark_with_bencher:
    name: Track benchmarks with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: trace4rs
      BENCHER_ADAPTER: rust_criterion
      BENCHER_TESTBED: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      - uses: bencherdev/bencher@main
      - name: Benchmark trace4rs with Bencher
        run: |
          bencher run \
          --if-branch "${{ github.event.pull_request.head.ref }}" \
          --else-if-branch "${{ github.event.pull_request.base.ref }}" \
          --else-if-branch main \
          --err \
          --github-actions "${{ secrets.GITHUB_TOKEN }}" \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          "cargo bench"
