name: Benchmark

on:
  push:
    branches: main

env:
  CARGO_TERM_COLOR: always
  BENCHER_PROJECT: trace4rs
  BENCHER_ADAPTER: rust_criterion
  BENCHER_TESTBED: ubuntu-latest

jobs:
  benchmark_main_with_bencher:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Track main benchmarks with Bencher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bencherdev/bencher@main
      - name: Benchmark trace4rs main with Bencher
        run: |
          bencher run \
          --branch main \
          --token "${{ secrets.BENCHER_API_TOKEN }}" \
          "cargo bench"
