name: Cargo

# This workflow run tests and build for each push

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature-**'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly-2023-10-25
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: "clippy, rustfmt"

      - name: Info
        run: |
          rustc --version
          cargo --version --verbose
          cargo clippy --version
          cargo fmt --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Spell
        run: cspell --config ./cspell.json "**/*.{rs|md}"

  cargo:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features_arg:
          - --features serde
        toolchain:
          - stable
          - beta
          - nightly
          - nightly-2023-10-25
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: taiki-e/install-action@nextest

      - name: Info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Test
        run: |
          cargo check
          cargo nextest run --all ${{ matrix.features_arg }}

      - name: Build
        run: |
          cargo build --release ${{ matrix.features_arg }}

  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: trace4rs
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: rust
      BENCHER_VERSION: 0.2.27
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          rustup update
          rustup toolchain install nightly
          wget https://github.com/bencherdev/bencher/releases/download/v${BENCHER_VERSION}/bencher_${BENCHER_VERSION}_amd64.deb
          sudo dpkg -i bencher_${BENCHER_VERSION}_amd64.deb
      - name: Benchmark with Bencher
        run: bencher run --if-branch $GITHUB_REF_NAME --err "cargo bench"

