name: Cargo

# This workflow run tests and build for each push

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature-**'

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly-2022-06-25
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
          rustup +${{ matrix.toolchain }} component add clippy rustfmt

      - name: Toolchain info
        run: |
          cargo +${{ matrix.toolchain }} --version --verbose
          cargo +${{ matrix.toolchain }} clippy --version
          cargo +${{ matrix.toolchain }} fmt --version

      - name: Lint
        run: |
          cargo +${{ matrix.toolchain }} fmt -- --check
          cargo +${{ matrix.toolchain }} clippy -- -D warnings

  cargo:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features_arg:
          - --features serde
        toolchain:
          - stable
          - beta
          - nightly
          - nightly-2022-06-25
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update ${{ matrix.toolchain }}

      - name: Toolchain info
        run: |
          cargo +${{ matrix.toolchain }} --version --verbose
          rustc +${{ matrix.toolchain }} --version

      - name: Test
        run: |
          cargo +${{ matrix.toolchain }} check
          cargo +${{ matrix.toolchain }} test --all ${{ matrix.features_arg }}

      - name: Build
        run: |
          cargo +${{ matrix.toolchain }} build ${{ matrix.features_arg }} --release

  benchmark:
    if: github.ref == 'refs/heads/main'
    name: Run benchmarks
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: trace4rs
      BENCHER_BRANCH: main
      BENCHER_TESTBED: ubuntu-latest
      BENCHER_ADAPTER: rust_criterion
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: bencherdev/bencher@main
      - name: Install Rust Nightly
        run: |
          rustup update
          rustup toolchain install nightly
      - name: Benchmark with Bencher
        run: bencher run --err "cargo bench"

