name: Cargo

# This workflow run tests and build for each push

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature-**'

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features_arg:
          - --features serde
          -
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Update local toolchain
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo test --all ${{ matrix.features_arg }}

      - name: Build
        run: |
          cargo build ${{ matrix.features_arg }} --release
